version: '3'

services:
  write-to-cache:
    build:
      context: .
      dockerfile: dockerfiles/cache_manipulator.Dockerfile
      target: write-to-cache

  app:
    build:
      context: .
      dockerfile: dockerfiles/app.Dockerfile
      target: run